命令稿啟動於 2018年03月19日 上午 11:19:30
]0;~
[32mUser@LAPTOP-5BMKG86V [33m~[0m
$ w[Kwhoami; pwd
User
/home/User
]0;~
[32mUser@LAPTOP-5BMKG86V [33m~[0m
$  git config -l
user.name=aa86twtw
user.email=aa86twtw@gmail.com
]0;~
[32mUser@LAPTOP-5BMKG86V [33m~[0m
$  git clone https://github.com/<your github account>/lab1.gitaa[K[K[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.gita/lab1.gita/lab1.git8/lab1.git6/lab1.gitt/lab1.gitw/lab1.gitt/lab1.gitw/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;~
[32mUser@LAPTOP-5BMKG86V [33m~[0m
$ exit

命令稿已於 2018年03月19日 上午 11:22:01
 完成